#set up properties
PROJECT_ID: qwiklabs-gcp-03-db9078619083

management:
    security:
        enabled: false

server:
    port: ${DEFAULT_PORT:80}

spring:
    application:
        name: app-translator