#set up properties
PROJECT_ID: qwiklabs-gcp-03-091a14f6d2dc

management:
    security:
        enabled: false

server:
    port: ${DEFAULT_PORT:80}

spring:
    application:
        name: app-translator