#set up properties
PROJECT_ID:qwiklabs-gcp-01-f2bd785bc3ee

management:
    security:
        enabled: false

server:
    port: ${DEFAULT_PORT:8090}

spring:
    application:
        name: app-translator